### ISSUE TITLE
[BUG] Traceback upon calling player nickname 

### ISSUE THREAD

**Issue by zwartkop2** [DrakeTheDuelist/MAS-AprilFirst#1]
[traceback.txt](https://github.com/DrakeTheDuelist/MAS-AprilFirst/files/6241668/traceback.txt)
![immediately after opting to ignore](https://user-images.githubusercontent.com/79435778/113256803-8af86000-927e-11eb-918f-02f3d0a43c00.png)

**Comment by wboorman** [comment]
Yes, I see what happened. No, I don't know why it never came up in testing.

Parenthetically, I _pray to God_ the idea of pulling some stunt on a specific date never, ever, ever comes up in anything I develop for MAS ever again. _Ever_.
